package plan

import (
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// Plan represents the structured plan generated by the model.
type Plan struct {
	Title            string     `json:"title"`
	Summary          string     `json:"summary"`
	Confidence       float64    `json:"confidence"`
	EstimatedSteps   int        `json:"estimated_steps"`
	Risks            []string   `json:"risks"`
	Steps            []PlanStep `json:"steps"`
	FilesAffected    []string   `json:"files_affected"`
	RollbackStrategy string     `json:"rollback_strategy"`
}

// PlanStep represents a single step within a Plan.
type PlanStep struct {
	ID              int    `json:"id"`
	Description     string `json:"description"`
	Type            string `json:"type"` // file_edit | shell | git | docker | info
	Target          string `json:"target"`
	Reversible      bool   `json:"reversible"`
	RequiresConfirm bool   `json:"requires_confirm"`
}

// Validate checks if the Plan has all required fields populated and valid values.
func (p *Plan) Validate() error {
	if strings.TrimSpace(p.Title) == "" {
		return errors.New("missing required field: title")
	}
	if strings.TrimSpace(p.Summary) == "" {
		return errors.New("missing required field: summary")
	}
	if len(p.Steps) == 0 {
		return errors.New("missing required field: steps (must contain at least one step)")
	}
	for i, step := range p.Steps {
		if step.ID <= 0 {
			return fmt.Errorf("step %d: missing or invalid step ID", i+1)
		}
		if strings.TrimSpace(step.Description) == "" {
			return fmt.Errorf("step %d (ID %d): missing description", i+1, step.ID)
		}
		if strings.TrimSpace(step.Type) == "" {
			return fmt.Errorf("step %d (ID %d): missing step type", i+1, step.ID)
		}
		// Valid type values: file_edit, shell, git, docker, info
		validType := false
		for _, t := range []string{"file_edit", "shell", "git", "docker", "info"} {
			if step.Type == t {
				validType = true
				break
			}
		}
		if !validType {
			return fmt.Errorf("step %d (ID %d): invalid step type '%s'", i+1, step.ID, step.Type)
		}
	}
	return nil
}

// ParsePlanJSON parses a raw JSON string into a Plan, handling markdown code fences.
func ParsePlanJSON(raw string) (*Plan, error) {
	cleaned := strings.TrimSpace(raw)
	if strings.HasPrefix(cleaned, "```") {
		lines := strings.Split(cleaned, "\n")
		if len(lines) > 2 {
			endIdx := -1
			for i := len(lines) - 1; i > 0; i-- {
				if strings.HasPrefix(strings.TrimSpace(lines[i]), "```") {
					endIdx = i
					break
				}
			}
			if endIdx > 1 {
				cleaned = strings.Join(lines[1:endIdx], "\n")
			} else {
				cleaned = strings.Join(lines[1:], "\n")
			}
		}
	}
	cleaned = strings.TrimSpace(cleaned)

	var p Plan
	if err := json.Unmarshal([]byte(cleaned), &p); err != nil {
		return nil, fmt.Errorf("failed to unmarshal JSON: %w", err)
	}

	// Apply defaults for optional fields
	if p.Confidence <= 0 {
		p.Confidence = 0.7
	}
	if p.Risks == nil {
		p.Risks = []string{}
	}
	if p.FilesAffected == nil {
		p.FilesAffected = []string{}
	}
	if strings.TrimSpace(p.RollbackStrategy) == "" {
		p.RollbackStrategy = "No specific rollback strategy provided."
	}
	if p.EstimatedSteps <= 0 {
		p.EstimatedSteps = len(p.Steps)
	}

	// Validate required fields
	if err := p.Validate(); err != nil {
		return nil, fmt.Errorf("invalid plan schema: %w", err)
	}

	return &p, nil
}
